remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Navigation Plugin - BF2042 Portal Rules Editor
description: This is a plugin for the Battlefield Portal Browser Extension to provide navigational helper functions.
